function comment = commentDialbox
dialDone = dialog('Position',[300 300 550 500],'Name','Done');
movegui(dialDone,'center')
txt = uicontrol('Parent',dialDone,...
    'Style','text',...
    'FontSize',16,...
    'Position',[0 450 550 30],...
    'String','Congrats!');
txt2 = uicontrol('Parent',dialDone,...
    'Style','text',...
    'FontSize',16,...
    'Position',[0 420 550 30],...
    'String','You have finished the listening test.');
txt3 = uicontrol('Parent',dialDone,...
    'Style','text',...
    'FontSize',16,...
    'Position',[0 390 550 30],...
    'String','Thanks for your time!');
txt4 = uicontrol('Parent',dialDone,...
    'Style','text',...
    'FontSize',16,...
    'Position',[0 330 550 30],...
    'String','Please write any remarks you have on the experiment:');


editComment = uicontrol('Parent',dialDone,...
    'Style','edit',...
    'Position',[30 100 500 230],...
    'FontSize',16,...
    'Max',10,...
    'HorizontalAlignment','left',...
    'Callback',@editComment_callback);

btn = uicontrol('Parent',dialDone,...
    'Position',[200 25 150 50],...
    'String','Save & Close',...
    'FontSize',16,...
    'Callback','delete(gcf)');

comment = [];
% Wait for d to close before running to completion
uiwait(dialDone);
    function editComment_callback(editComment,event)
        comment = get(editComment,'String');
    end
end